const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{easyBackround: 0},
	{var: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Solid: 0},
	{SolidTile: 0},
	{Sine: 0},
	{MovingSolidTile: 0},
	{Jumpthru: 0},
	{JumpThruTile: 0},
	{Keyboard: 0},
	{Text: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Text2: 0},
	{Sprite5: 0},
	{meadiumBackround: 0},
	{HardBackround: 0},
	{DifficultBackround: 0},
	{challengingBackround: 0},
	{intensebackround: 0},
	{RemorselessBackround: 0},
	{insanebackround: 0},
	{extremebackround: 0},
	{terbackround: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Audio: 0},
	{Text3: 0},
	{Sprite8: 0},
	{Text4: 0},
	{score: 0},
	{Text6: 0},
	{Text5: 0}
];

self.InstanceType = {
	easyBackround: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	SolidTile: class extends self.ITiledBackgroundInstance {},
	MovingSolidTile: class extends self.ITiledBackgroundInstance {},
	JumpThruTile: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	meadiumBackround: class extends self.ITiledBackgroundInstance {},
	HardBackround: class extends self.ITiledBackgroundInstance {},
	DifficultBackround: class extends self.ITiledBackgroundInstance {},
	challengingBackround: class extends self.ITiledBackgroundInstance {},
	intensebackround: class extends self.ITiledBackgroundInstance {},
	RemorselessBackround: class extends self.ITiledBackgroundInstance {},
	insanebackround: class extends self.ITiledBackgroundInstance {},
	extremebackround: class extends self.ITiledBackgroundInstance {},
	terbackround: class extends self.ITiledBackgroundInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	score: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {}
}